[package]
org = "choreo"
name = "choreo_subscriptions"
version = "1.0.0-m1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "mssql-jdbc"
version = "8.0.17"
path = "libs/mssql-jdbc-9.2.1.jre11.jar"
groupId = "com.microsoft.sqlserver"
