[package]
org = "choreo"
name = "choreo_subscriptions"
version = "1.0.0-m1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.17"
path = "libs/mysql-connector-java-8.0.17.jar"
groupId = "mysql"
