[choreo.choreo_subscriptions.config.database]
url = "jdbc:mysql://localhost:3306/choreo?autoReconnect=true"
user = "root"
password = "password"
loginTimeout = 10000
useSsl = false
poolSize = 5
minIdle = 5

[choreo.choreo_subscriptions.config.redisClient]
host = "localhost:6379"
password = ""
cacheKeyPrefix = "choreo_subscriptions."
enableSsl = false
connectionTimeout = 500
connectionPooling = true
isClusterConnection = false
startTls = false
verifyPeer = false
database = 0
