[choreo.choreo_subscriptions.config.database]
url = "jdbc:sqlserver://localhost:1433;databaseName=choreo_subscriptions_db"
user = "SA"
loginTimeout = 10000
useSsl = false
poolSize = 5
minIdle = 5

[choreo.choreo_subscriptions.config.redisClient]
host = "localhost:6379"
cacheKeyPrefix = "choreo_subscriptions."
enableSsl = false
connectionTimeout = 500
connectionPooling = true
isClusterConnection = false
startTls = false
verifyPeer = false
database = 0
