resources:
  repositories:
    - repository: TEMPLATE_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise


trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

pr:
  branches:
    include:
      - '*'
      
pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: run-super-linter.yaml@TEMPLATE_REPOSITORY
    parameters:
      SUPER_LINTER_VERSION: v4
      OPTIONS: |-
        -e VALIDATE_YAML=true \
        -e VALIDATE_DOCKER=true \
        -e VALIDATE_SQL=true
