trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  SUPER_LINTER_VERSION: v4

steps:
  - script: |
      docker pull github/super-linter:$(SUPER_LINTER_VERSION)
      docker run \
        -e RUN_LOCAL=true \
        -e VALIDATE_YAML=true \
        -e VALIDATE_DOCKER=true \
        -e VALIDATE_SQL=true \
        -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter:$(SUPER_LINTER_VERSION)
    displayName: 'Code Scan using GitHub Super-Linter'
