# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.

trigger: none
pr:
  branches:
    include:
    - '*'

resources:
  containers:
  - container: choreo-ballerina
    image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina:swan-lake-beta1-azure-builder
  
pool:
  vmImage: 'ubuntu-latest'
  
variables:
  CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
  REPOSITORY: choreoipaas/choreo-subscriptions
  TAG: $(Build.SourceBranchName)-$(Build.SourceVersion)

container: choreo-ballerina

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- template: templates/subscriptions-build.yml

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    containerRegistry: 'wso2choreo-control-plane-acr'
    repository: $(REPOSITORY)
    tags: $(TAG)
    Dockerfile: 'Dockerfile'
    buildContext: '.'

- template: templates/trivy-docker-scan.yml
  parameters:
    registry: $(CONTAINER_REGISTRY)
    repository: $(REPOSITORY)
    tag: $(TAG)
