# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.

pr: none

trigger:
  batch: true
  branches:
    include:
    - predev

resources:
  containers:
  - container: choreo-ballerina
    image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina:swan-lake-beta1-azure-builder
jobs:
- job: DockerReleaseScanAndPush

  pool:
    vmImage: 'ubuntu-latest'

  container: choreo-ballerina

  variables:
    CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
    REPOSITORY: choreoipaas/choreo-subscriptions
    TAG: $(Build.SourceBranchName)-$(Build.SourceVersion)

  steps:
  - template: templates/susbcriptions-build.yml

  - template: templates/trivy-docker-scan.yml
    parameters:
      repository: $(REPOSITORY)
      tag: $(TAG)
      trivyExitCode: 0
      registry: $(CONTAINER_REGISTRY)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: $(TAG)
