# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.

pr: none

trigger:
  batch: true
  branches:
    include:
    - main

resources:
  repositories:
  - repository: common-templates
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    endpoint: choreo-cicd
  containers:
  - container: choreo-ballerina
    image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina:swan-lake-beta1-azure-builder

jobs:
- job: SubscriptionBuild
  container: choreo-ballerina
  steps:
  - template: templates/subscriptions-build.yml

  - template: hangouts-notify.yml@common-templates
    parameters:
      organizationName: choreo-devops
      webhookUrl: https://chat.googleapis.com/v1/spaces/AAAA-5OLQuo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=JJMhwqOkYAK4Afyep2sx86i-FWhFFaWmoRNQ_5yqlR4%3D
      repositoryPath: $(Agent.BuildDirectory)/choreo-subscriptions

- job: DockerReleaseScanAndPush
  dependsOn: SubscriptionBuild
  condition: succeeded()

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
    REPOSITORY: choreoipaas/choreo-subscriptions
    TAG: $(Build.SourceBranchName)-$(Build.SourceVersion)

  steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: |
        $(TAG)
        latest

  - template: templates/trivy-docker-scan.yml
    parameters:
      repository: $(REPOSITORY)
      tag: $(TAG)
      registry: $(CONTAINER_REGISTRY)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        $(TAG)
        latest

  - template: update-image-in-cp-overlays.yml@common-templates
    parameters:
      DOCKER_IMAGE_LIST:
      - ${{ variables.CONTAINER_REGISTRY }}/${{ variables.REPOSITORY }}:$(TAG)

  - template: hangouts-notify.yml@common-templates
    parameters:
      organizationName: choreo-devops
      webhookUrl: https://chat.googleapis.com/v1/spaces/AAAA-5OLQuo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=JJMhwqOkYAK4Afyep2sx86i-FWhFFaWmoRNQ_5yqlR4%3D
      repositoryPath: $(Agent.BuildDirectory)/choreo-subscriptions
