pr: none

trigger:
  batch: true
  branches:
    include:
      - refs/tags/v*

resources:
  containers:
  - container: choreo-ballerina
    image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina:swan-lake-beta1-azure-builder

jobs:
- job: SubscriptionBuild
  container: choreo-ballerina
  steps:
  - template: templates/subscriptions-build.yml

- job: DockerReleaseScanAndPush
  dependsOn: SubscriptionBuild
  condition: succeeded()

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
    REPOSITORY: choreoipaas/choreo-subscriptions
    TAG: $(Build.SourceBranchName)

  steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: |
        $(TAG)
        
  - template: templates/trivy-docker-scan.yml
    parameters:
      repository: $(REPOSITORY)
      tag: $(TAG)
      registry: $(CONTAINER_REGISTRY)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        $(TAG)
